config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "restaurants/:restaurant_id/reviews/new", to: "reviews#new", as: :new_review
  # post "restaurants/:restaurant_id/reviews/", to: "reviews#create", as: :create_review
  resources :restaurants do
    resources :reviews, except: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, inclusion: {in: ["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: 0..5}
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants =  Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [:show, :edit, :update, :destroy]
  before_action :find_restaurant, only: [:edit, :update, :show]

  def index
    @reviews =  Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
    @review.restaurant_id = @restaurant.id
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to restaurant_review_path(@restaurant, @review)
    else
      render :edit
    end
  end

  def destroy
    restaurant = @review.restaurant
    @review.destroy
    redirect_to restaurant_path(restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit restaurant <%= @restaurant.name %></h1>

  <%= render partial: "form" %>

  <%= link_to "Go back", restaurant_path(@restaurant) %>
 </div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= restaurant.name %>
      <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>
      <%= link_to "🗑", restaurant_path(restaurant), method: "delete"%>
    </li>
  <% end %>
</ul>

 <%= link_to 'Create new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Create a new restaurant</h1>

  <%= render partial: "form" %>

  <%= link_to "Back to restaurant list", restaurants_path %>
 </div>

app/views/restaurants/show.html.erb
<div class="container">
<h1><%= @restaurant.name %></h1>

<p>Address: <%= @restaurant.address %></p>
<p>Phone number: <%= @restaurant.phone_number %></p>
<p>Category: <%= @restaurant.category %></p>
<h2>Reviews: </h2>
<% @restaurant.reviews.each  do |review| %>
  <div class="review">
    <p>Rating: <%= "⭑" * review.rating %></p>
    <p><%= review.content %></p>
    <%= link_to "Show review", restaurant_review_path(@restaurant, review) %>
  </div>
<% end %>
<h3>Add new review:</h3>
<%= simple_form_for([@restaurant,Review.new]) do |f| %>
    <%= f.input :rating, as: :integer, collection: 0..5 %>
    <%= f.input :content, as: :text%>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

<%= link_to "Edit details", edit_restaurant_path(@restaurant) %>
<%= link_to "Delete restaurant", restaurant_path(@restaurant), method: "delete"%>
<%= link_to "Back to restaurant list", restaurants_path %>
</div>

app/views/reviews/_form.html.erb
  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.input :rating, as: :integer, collection: 0..5 %>
    <%= f.input :content, as: :text%>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>

<%= render partial: "form" %>

<%= link_to "Go back to restaurant", restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Write new review for restaurant <%= @restaurant.name %></h1>

<%= render partial: "form" %>

<%= link_to "Go back to restaurant", restaurant_path(@restaurant) %>

app/views/reviews/show.html.erb
<h1>A review for restaurant <%= @restaurant.name %></h1>

<div class="review">
    <p>Rating: <%= "⭑" * @review.rating %></p>
    <p><%= @review.content %></p>
    <%= link_to "Go back", restaurant_path(@restaurant) %>
    <%= link_to "Edit review", edit_restaurant_review_path(@restaurant, @review) %>
    <%= link_to "🗑", restaurant_review_path(@restaurant, @review), method: "delete"%>
</div>